#PEGAR A INFORMAÇÃO EM SEGUNDOS E EXPRESSAR EM HORAS

minuto = int(input("QUANTOS SEGUNDOS VOCE USOU ?"))
a1 = minuto/3600
a2 = a1*60
print("SE EU TRANSFORMAR ISSO PARA MINUTOS FICA :", a2 ,"minutos")